# Generated by Django 2.1 on 2020-03-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
