# Generated by Django 3.0.3 on 2020-02-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_album_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=100)),
                ('answers', models.CharField(max_length=100)),
				('node_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=100)),
                ('answers', models.CharField(max_length=100)),
				('node_num', models.IntegerField()),
            ],
        ),
    ]
