# Generated by Django 2.1 on 2020-03-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200311_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecode',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
