# Generated by Django 2.1 on 2020-03-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200309_2101'),
    ]

    operations = [

    ]
