# Generated by Django 2.1 on 2020-03-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200308_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='longtitude',
            field=models.IntegerField(default=0),
        ),
    ]
