# Generated by Django 3.0.3 on 2020-02-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
