# Generated by Django 2.1 on 2020-03-10 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200309_2253'),
    ]

    operations = [


    ]
