# Generated by Django 2.1 on 2020-03-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200308_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='latitude',
            field=models.IntegerField(default=-1.1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='longtitude',
            field=models.IntegerField(default=-1.1),
        ),
    ]
