# Generated by Django 2.1 on 2020-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='node_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
