# Generated by Django 2.1 on 2020-03-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecode',
            name='questionNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questions',
            name='hints',
            field=models.CharField(default='', max_length=100),
        ),
    ]
