# Generated by Django 2.1 on 2020-02-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questions_node_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='hints',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
