# Generated by Django 2.1 on 2020-03-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200305_1513'),
    ]

    operations = [
       
    ]
