# Generated by Django 2.1 on 2020-03-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200308_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='latitude',
            field=models.FloatField(default='-1.1'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='longtitude',
            field=models.FloatField(default='-1.1'),
        ),
    ]
