# Generated by Django 2.1 on 2020-03-10 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200310_0142'),
    ]

    operations = [


    ]
