# Generated by Django 2.1 on 2020-03-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200308_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='longtitude',
            field=models.FloatField(),
        ),
    ]
