# Generated by Django 2.1 on 2020-03-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_gamecode_routeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecode',
            name='map',
            field=models.CharField(default='False', max_length=50),
        ),
    ]
