# Generated by Django 2.1 on 2020-03-10 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200310_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecode',
            name='routeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Routes'),
        ),
        migrations.AddField(
            model_name='questions',
            name='latitude',
            field=models.FloatField(default=-1.1),
        ),
        migrations.AddField(
            model_name='questions',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='questions',
            name='longtitude',
            field=models.FloatField(default=-1.1),
        ),
        migrations.AddField(
            model_name='questions',
            name='routeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Routes'),
        ),
        migrations.AlterField(
            model_name='gamecode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
