# Generated by Django 2.1 on 2020-03-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_gamecode_map'),
        ('app', '0002_tables'),
    ]

    operations = [
    ]
