# Generated by Django 2.1 on 2020-03-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200308_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
