# Generated by Django 2.1 on 2020-03-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='latitude',
            field=models.FloatField(default=-1.1),
        ),
        migrations.AddField(
            model_name='questions',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='questions',
            name='longtitude',
            field=models.FloatField(default=-1.1),
        ),
    ]
