# Generated by Django 2.1.15 on 2020-03-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('devID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='gameMaster',
            fields=[
                ('GMID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('HintText', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('HintNo', models.IntegerField()),
                ('Routes_NodeID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('routeID', models.IntegerField(primary_key=True, serialize=False)),
                ('Node', models.CharField(max_length=45)),
                ('NodeID', models.IntegerField()),
                ('RouteName', models.CharField(max_length=45)),
                ('gameMaster_GMID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.gameMaster')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='questions',
            name='hints',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
        migrations.AddField(
            model_name='players',
            name='user_userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User'),
        ),
        migrations.AddField(
            model_name='hints',
            name='Routes_routeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Routes'),
        ),
        migrations.AddField(
            model_name='groups',
            name='Players_playerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Players'),
        ),
        migrations.AddField(
            model_name='gamemaster',
            name='user_userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User'),
        ),
        migrations.AddField(
            model_name='developers',
            name='user_userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User'),
        ),
    ]
